# Generated by Django 3.1 on 2022-05-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='team',
        ),
    ]
