# Generated by Django 4.1.7 on 2023-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerApp', '0004_district_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='flower',
            unique_together={('name', 'category')},
        ),
    ]
