# Generated by Django 4.1.7 on 2023-04-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerApp', '0005_alter_flower_name_alter_flower_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flower',
            unique_together=set(),
        ),
    ]
