# Generated by Django 4.1.7 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerApp', '0006_alter_flower_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
